"""Added User and Staff tables

Revision ID: 006822323c9d
Revises: c3cd7ce7cfb1
Create Date: 2025-09-19 16:38:21.920205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '006822323c9d'
down_revision = 'c3cd7ce7cfb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emergency_contact_frst_name', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact_last_name', sa.String(length=64), nullable=True))
        batch_op.drop_column('emergency_contact_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emergency_contact_name', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('emergency_contact_last_name')
        batch_op.drop_column('emergency_contact_frst_name')

    # ### end Alembic commands ###
