"""Added User and Staff tables

Revision ID: 1668582e2e3f
Revises: e83a630a0ef8
Create Date: 2025-09-04 17:30:36.223129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1668582e2e3f'
down_revision = 'e83a630a0ef8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('responsible_first_name', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('responsible_last_name', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('responsible_email', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('responsible_phone', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('responsible_address', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('responsible_city', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('responsible_state', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('responsible_zip_code', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_column('responsible_zip_code')
        batch_op.drop_column('responsible_state')
        batch_op.drop_column('responsible_city')
        batch_op.drop_column('responsible_address')
        batch_op.drop_column('responsible_phone')
        batch_op.drop_column('responsible_email')
        batch_op.drop_column('responsible_last_name')
        batch_op.drop_column('responsible_first_name')

    # ### end Alembic commands ###
