"""Added User and Staff tables

Revision ID: 35f53e629fe2
Revises: 3b2d28024e57
Create Date: 2025-09-01 14:48:56.039600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35f53e629fe2'
down_revision = '3b2d28024e57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membership_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('duration_months', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membership_types', schema=None) as batch_op:
        batch_op.drop_column('duration_months')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
