"""Added User and Staff tables

Revision ID: 63d613622c24
Revises: 6fbeb3abcee0
Create Date: 2025-08-31 16:29:23.960720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63d613622c24'
down_revision = '6fbeb3abcee0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_record', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
