"""Added User and Staff tables

Revision ID: 6fbeb3abcee0
Revises: b0dcad8c793f
Create Date: 2025-08-31 16:27:33.457334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fbeb3abcee0'
down_revision = 'b0dcad8c793f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_session', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
