"""Added User and Staff tables

Revision ID: b0dcad8c793f
Revises: b7e733b61dab
Create Date: 2025-08-31 15:34:36.119235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0dcad8c793f'
down_revision = 'b7e733b61dab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membership_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enroll_price', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('membership_price', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.drop_column('price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membership_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.NUMERIC(precision=10, scale=2), nullable=False))
        batch_op.drop_column('membership_price')
        batch_op.drop_column('enroll_price')

    # ### end Alembic commands ###
