"""Added User and Staff tables

Revision ID: e6cbdb3dfe29
Revises: 006822323c9d
Create Date: 2025-09-19 16:43:07.170934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6cbdb3dfe29'
down_revision = '006822323c9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emergency_contact_first_name', sa.String(length=64), nullable=True))
        batch_op.drop_column('emergency_contact_frst_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emergency_contact_frst_name', sa.VARCHAR(length=64), nullable=True))
        batch_op.drop_column('emergency_contact_first_name')

    # ### end Alembic commands ###
