"""Added User and Staff tables

Revision ID: e83a630a0ef8
Revises: 35f53e629fe2
Create Date: 2025-09-02 20:43:53.730737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e83a630a0ef8'
down_revision = '35f53e629fe2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_time', sa.DateTime(), nullable=True))
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=True))
        batch_op.drop_column('session_time')

    # ### end Alembic commands ###
