# Generated by Django 5.2.9 on 2025-12-28 18:24

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import localflavor.us.models
import multiselectfield.db.fields
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("adult", "Adult"),
                            ("kids", "Kids"),
                            ("open", "Open"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "days_of_week",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            ("mon", "Monday"),
                            ("tue", "Tuesday"),
                            ("wed", "Wednesday"),
                            ("thu", "Thursday"),
                            ("fri", "Friday"),
                            ("sat", "Saturday"),
                            ("sun", "Sunday"),
                        ],
                        max_length=27,
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(max_length=5000)),
                ("enroll_price", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "membership_price",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("duration_months", models.IntegerField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "is_coach",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user is a coach.",
                        verbose_name="coach status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user is a staff.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to.",
                        related_name="crm_users",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="crm_user_permissions",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "member_type",
                    models.CharField(
                        choices=[("adult", "Adult"), ("child", "Child")],
                        default="adult",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("male", "Male"), ("female", "Female")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("date_of_birth", models.DateField()),
                ("join_date", models.DateTimeField(auto_now_add=True)),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=64)),
                (
                    "state",
                    localflavor.us.models.USStateField(
                        blank=True, default="IL", max_length=2, null=True
                    ),
                ),
                ("zip_code", models.CharField(max_length=10)),
                (
                    "belt_rank",
                    models.CharField(
                        choices=[
                            ("white", "White"),
                            ("gray-white", "Gray / White"),
                            ("gray", "Gray"),
                            ("gray-black", "Gray / Black"),
                            ("yellow-white", "Yellow / White"),
                            ("yellow", "Yellow"),
                            ("yellow-black", "Yellow / Black"),
                            ("orange-white", "Orange / White"),
                            ("orange", "Orange"),
                            ("orange-black", "Orange / Black"),
                            ("green-white", "Green / White"),
                            ("green", "Green"),
                            ("green-black", "Green / Black"),
                            ("blue", "Blue"),
                            ("purple", "Purple"),
                            ("brown", "Brown"),
                            ("black", "Black"),
                            ("red-black", "Red & Black"),
                            ("red-white", "Red & White"),
                            ("red", "Red"),
                        ],
                        default="white",
                        max_length=50,
                    ),
                ),
                (
                    "stripes",
                    models.SmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                ("photo", models.URLField(blank=True, null=True)),
                ("membership_start_date", models.DateField(blank=True, null=True)),
                ("membership_end_date", models.DateField(blank=True, null=True)),
                ("waivers_signed", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="members",
                        to="crm.plan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("spouse", "Spouse"),
                            ("parent", "Parent"),
                            ("guardian", "Guardian"),
                            ("sibling", "Sibling"),
                            ("child", "Child"),
                            ("friend", "Friend"),
                        ],
                        default="parent",
                        max_length=50,
                    ),
                ),
                (
                    "contact_type",
                    models.CharField(
                        choices=[
                            ("responsible", "Responsible"),
                            ("emergency", "Emergency Contact"),
                        ],
                        default="responsible",
                        max_length=20,
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="crm.member",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "Class",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance",
                        to="crm.class",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance",
                        to="crm.member",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("payment_date", models.DateField()),
                ("payment_method", models.CharField(max_length=50)),
                ("status", models.CharField(default="paid", max_length=50)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membership_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plan_id",
                        to="crm.plan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("role", models.CharField(max_length=120)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("male", "Male"), ("female", "Female")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=200, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=50, null=True)),
                ("zip_code", models.CharField(blank=True, max_length=10, null=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("join_date", models.DateField()),
                (
                    "belt_rank",
                    models.CharField(
                        choices=[
                            ("white", "White"),
                            ("gray-white", "Gray / White"),
                            ("gray", "Gray"),
                            ("gray-black", "Gray / Black"),
                            ("yellow-white", "Yellow / White"),
                            ("yellow", "Yellow"),
                            ("yellow-black", "Yellow / Black"),
                            ("orange-white", "Orange / White"),
                            ("orange", "Orange"),
                            ("orange-black", "Orange / Black"),
                            ("green-white", "Green / White"),
                            ("green", "Green"),
                            ("green-black", "Green / Black"),
                            ("blue", "Blue"),
                            ("purple", "Purple"),
                            ("brown", "Brown"),
                            ("black", "Black"),
                            ("red-black", "Red & Black"),
                            ("red-white", "Red & White"),
                            ("red", "Red"),
                        ],
                        default="white",
                        max_length=50,
                    ),
                ),
                (
                    "stripes",
                    models.SmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                ("photo", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="class",
            name="instructor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classes",
                to="crm.staff",
            ),
        ),
        migrations.CreateModel(
            name="BeltPromotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_rank",
                    models.CharField(
                        choices=[
                            ("white", "White"),
                            ("gray-white", "Gray / White"),
                            ("gray", "Gray"),
                            ("gray-black", "Gray / Black"),
                            ("yellow-white", "Yellow / White"),
                            ("yellow", "Yellow"),
                            ("yellow-black", "Yellow / Black"),
                            ("orange-white", "Orange / White"),
                            ("orange", "Orange"),
                            ("orange-black", "Orange / Black"),
                            ("green-white", "Green / White"),
                            ("green", "Green"),
                            ("green-black", "Green / Black"),
                            ("blue", "Blue"),
                            ("purple", "Purple"),
                            ("brown", "Brown"),
                            ("black", "Black"),
                            ("red-black", "Red & Black"),
                            ("red-white", "Red & White"),
                            ("red", "Red"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "old_stripes",
                    models.SmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                (
                    "new_rank",
                    models.CharField(
                        choices=[
                            ("white", "White"),
                            ("gray-white", "Gray / White"),
                            ("gray", "Gray"),
                            ("gray-black", "Gray / Black"),
                            ("yellow-white", "Yellow / White"),
                            ("yellow", "Yellow"),
                            ("yellow-black", "Yellow / Black"),
                            ("orange-white", "Orange / White"),
                            ("orange", "Orange"),
                            ("orange-black", "Orange / Black"),
                            ("green-white", "Green / White"),
                            ("green", "Green"),
                            ("green-black", "Green / Black"),
                            ("blue", "Blue"),
                            ("purple", "Purple"),
                            ("brown", "Brown"),
                            ("black", "Black"),
                            ("red-black", "Red & Black"),
                            ("red-white", "Red & White"),
                            ("red", "Red"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "new_stripes",
                    models.SmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                ("promotion_date", models.DateField()),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="belt_promotions",
                        to="crm.member",
                    ),
                ),
                (
                    "promoted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="promotions_given",
                        to="crm.staff",
                    ),
                ),
            ],
        ),
    ]
