# Generated by Django 5.2.9 on 2025-12-30 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(code=lambda apps, schema_editor: None, reverse_code=lambda apps, schema_editor: None),
        ]
