# Generated by Django 5.2.9 on 2025-12-30 20:27

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_auto_20251230_1332"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None
            ),
        ),
    ]
